name: social_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.4
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  lottie: ^1.4.3
  fluttertoast: ^8.1.1
  image_picker: ^0.8.6
  buildcondition: ^0.0.4
  timeago: ^3.3.0
  uuid: ^3.0.7
  page_transition: ^2.0.9
  intl: ^0.17.0
  flutter_local_notifications: ^12.0.4
  http: ^0.13.5

  # Firebase
  firebase_core: ^2.3.0
  firebase_auth: ^4.0.2
  firebase_storage: ^11.0.6
  cloud_firestore: ^4.1.0
  firebase_messaging: ^14.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/json/
     - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

